---
development:
  dialect: mysql
  database: {{envOr "DATABASE_MASTER_DATABASE" "crud"}}
  host: {{envOr "DATABASE_MASTER_HOST" "localhost"}}
  port: {{envOr "DATABASE_MASTER_PORT" "3309"}}
  user: {{envOr "DATABASE_MASTER_USER" "root"}}
  password: {{envOr "DATABASE_MASTER_PASSWORD" "1fN82Avd7TT5Bad2"}}
  pool: 3